/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.ISEError;
import io.swagger.model.Login;
import io.swagger.model.ModelError;
import io.swagger.model.Token;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import javax.validation.constraints.*;
import javax.validation.Valid;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-09-27T17:51:23.206-04:00")

@Api(value = "login", description = "the login API")
public interface LoginApi {

    @ApiOperation(value = "", notes = "Allow users to log in and get token", response = Token.class, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Token.class),
        @ApiResponse(code = 400, message = "Bad Request", response = ModelError.class),
        @ApiResponse(code = 401, message = "Invalid username or password", response = ModelError.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ISEError.class) })
    
    @RequestMapping(value = "/login",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Token> loginPost(@ApiParam(value = ""  )  @Valid @RequestBody Login body);

}
